### PR TITLE
Fix issue #33

### PR DESCRIPTION
**Pull request by DavisDevasia**
This PR fixes issue #33

### CODE REVIEW

**Review by deniszpua — APPROVED** [review]
Thanks, @DavisDevasia, for spotting the bug!

**Comment by deniszpua** [comment]
Fix #33

**Comment by DavisDevasia** [comment]
Hi @deniszpua I had pushed two additional commits to my master branch after I have created this PR.
I didn't know it would automatically get included in the PR. My apologies.

You might need to revert last two of the three commits. Only the first one is relevant for the issue.

**Comment by deniszpua** [comment]
No worries @DavisDevasia. Those changes are okayish as well.

**Pull request merged**
