### PR TITLE
Added documentation/blog link for android/kotlin

### PR DESCRIPTION
**Pull request by thenishchalraj**
I struggling a lot for implementing this library for android using kotlin as the blogs and other articles available are all using java and others. So wanted to help the community  with the full documentation of the library for the major functions available for android w.r.t. kotlin.

### CODE REVIEW

**Comment by deniszpua** [comment]
@thenishchalraj Thanks for the awesome content!
We would highly appreciate, if that awesome blogpost will appear in [HyperTrack Blog](https://www.hypertrack.com/blog/) as a guest post, to keep it accessible for customers disregards medium paywall. Adding a link to our blog in medium article footer is highly welcome also. LMK, how we can progress through this.

**Comment by thenishchalraj** [comment]
Hey @deniszpua I just saw this in the morning, I am already feeling blessed. Thanks a lot.
Putting this as a guest post on HyperTrack Blog is a great idea. We can proceed with it.

**Comment by deniszpua** [comment]
@thenishchalraj Check out your mail box for the blog invitation. 
LMK, if you need any help with the post.

**Comment by thenishchalraj** [comment]
@deniszpua Can you connect through mail and let me know how it goes?

**Comment by deniszpua** [comment]
> @deniszpua Can you connect through mail and let me know how it goes?

@thenishchalraj I sent an email to address that specified in your github profile.

**Pull request merged**
